CREATE TABLE validations_collect_point (
  id SERIAL,
  social_reason VARCHAR(200) NOT NULL,
  cnpj VARCHAR(19) NOT NULL,
  phone VARCHAR(11) NOT NULL,
  biography VARCHAR(400) NOT NULL,
  hours_of_operation VARCHAR(50) NOT NULL,
  days_of_operation VARCHAR(50) NOT NULL,
  operating_status VARCHAR(50) DEFAULT 'ATIVO',
  -- reason_for_change VARCHAR(50) NOT NULL,
  -- data_time_for_change TIMESTAMP,
  delivery_type VARCHAR [] NOT NULL,
  city VARCHAR(100) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  number INTEGER NOT NULL,
  zipcode VARCHAR(8) NOT NULL,
  district VARCHAR(50) NOT NULL,
  street VARCHAR(70) NOT NULL,
  types_of_materials_accepted VARCHAR [] NOT NULL,
  validation_type VARCHAR(50) NOT NULL CHECK (validation_type = 'mudança_de_perfil'),
  validation_status VARCHAR(50) DEFAULT 'PENDENTE',
  user_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);
